/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Rocket(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/rocket.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Cube001"
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.Red}
          position={[1.43, 1.58, -0.12]}
          rotation={[0, 0, -0.56]}
        />
        <mesh
          name="Cube003"
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials.Red}
          position={[0.02, 1.58, 1.42]}
          rotation={[0.56, -Math.PI / 2, 0]}
        />
        <mesh
          name="Cube002"
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials.Red}
          position={[-1.48, 1.58, -0.12]}
          rotation={[Math.PI, 0, 2.58]}
        />
        <mesh
          name="Cube004"
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials.Red}
          position={[0.02, 1.58, -1.52]}
          rotation={[-0.56, Math.PI / 2, 0]}
        />
        
        <group name="Cube" position={[0, -8.54, 0]} scale={[0.89, 1, 0.89]}>
          <mesh
            name="Cube001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials.Red}
          />

          <mesh
            name="Cube001_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_2.geometry}
            material={materials.White}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/rocket.glb");

